/* Generated By:JJTree: Do not edit this line. AstEdgeParse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package puf.m2.rcw.edgelist.parser;

public class AstEdgeParse extends SimpleNode {
    public AstEdgeParse(int id) {
        super(id);
    }

    public AstEdgeParse(EdgeListParser p, int id) {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=f5db42e40f304a06062ef856e1f15fe4 (do not edit this
 * line)
 */
