/* Generated By:JJTree: Do not edit this line. AstEdge.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package puf.m2.rcw.edgelist.parser;

public class AstEdge extends SimpleNode {
    public AstEdge(int id) {
        super(id);
    }

    public AstEdge(EdgeListParser p, int id) {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=9247e922aa004bd0b238f78b7e721815 (do not edit this
 * line)
 */
