/* Generated By:JJTree: Do not edit this line. AstVertex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package puf.m2.rcw.edgelist.parser;

public class AstVertex extends SimpleNode {
    private String name;

    public AstVertex(int id) {
        super(id);
    }

    public AstVertex(EdgeListParser p, int id) {
        super(p, id);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
/*
 * JavaCC - OriginalChecksum=718d65c803ef7b3e3fb87cd878b66234 (do not edit this
 * line)
 */
