/* Generated By:JavaCC: Do not edit this line. EdgeListParserTreeConstants.java Version 5.0 */
package puf.m2.rcw.edgelist.parser;

public interface EdgeListParserTreeConstants {
    public int JJTEDGEPARSE = 0;
    public int JJTEDGE = 1;
    public int JJTVERTEX = 2;

    public String[] jjtNodeName = { "EdgeParse", "Edge", "Vertex", };
}
/*
 * JavaCC - OriginalChecksum=01d5580190b8df979d3f30404bbcf81d (do not edit this
 * line)
 */
