/* Generated By:JJTree&JavaCC: Do not edit this line. EdgeListParserConstants.java */
package puf.m2.rcw.edgelist.parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface EdgeListParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int OPLUS = 5;
    /** RegularExpression Id. */
    int LP = 6;
    /** RegularExpression Id. */
    int RP = 7;
    /** RegularExpression Id. */
    int COMMA = 8;
    /** RegularExpression Id. */
    int NUMBER = 9;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = { "<EOF>", "\" \"", "\"\\n\"", "\"\\r\"",
            "\"\\r\\n\"", "\"oplus\"", "\"(\"", "\")\"", "\",\"", "<NUMBER>", };

}
