/* Generated By:JJTree: Do not edit this line. AstReducedTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package puf.m2.rcw.reducedterm.parser;

public class AstReducedTerm extends SimpleNode {
    public AstReducedTerm(int id) {
        super(id);
    }

    public AstReducedTerm(ReducedTermParser p, int id) {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=4ddfe5be5486bb7b393c7fe4e50f4612 (do not edit this
 * line)
 */
