/* Generated By:JJTree: Do not edit this line. AstReducedTermParse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package puf.m2.rcw.reducedterm.parser;

public class AstReducedTermParse extends SimpleNode {
    public AstReducedTermParse(int id) {
        super(id);
    }

    public AstReducedTermParse(ReducedTermParser p, int id) {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=4706f56946c56ab68c9777046c19c5eb (do not edit this
 * line)
 */
