/* Generated By:JJTree: Do not edit this line. AstVertex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package puf.m2.rcw.reducedterm.parser;

public class AstVertex extends SimpleNode {
    private String name;

    public AstVertex(int id) {
        super(id);
    }

    public AstVertex(ReducedTermParser p, int id) {
        super(p, id);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String toString() {
        return "vertex : " + name;
    }

}
/*
 * JavaCC - OriginalChecksum=be8906b3e458f15b4eb417fe58548e1f (do not edit this
 * line)
 */
