/* Generated By:JavaCC: Do not edit this line. ReducedTermParserTreeConstants.java Version 5.0 */
package puf.m2.rcw.reducedterm.parser;

public interface ReducedTermParserTreeConstants {
    public int JJTREDUCEDTERMPARSE = 0;
    public int JJTREDUCEDTERM = 1;
    public int JJTVERTEX = 2;

    public String[] jjtNodeName = { "ReducedTermParse", "ReducedTerm",
            "Vertex", };
}
/*
 * JavaCC - OriginalChecksum=da4d84d3fd4aa38a2eb61daa9466a18e (do not edit this
 * line)
 */
