/* Generated By:JJTree&JavaCC: Do not edit this line. ReducedTermParserConstants.java */
package puf.m2.rcw.reducedterm.parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface ReducedTermParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int OPLUS = 5;
    /** RegularExpression Id. */
    int LP = 6;
    /** RegularExpression Id. */
    int RP = 7;
    /** RegularExpression Id. */
    int LSB = 8;
    /** RegularExpression Id. */
    int RSB = 9;
    /** RegularExpression Id. */
    int COMMA = 10;
    /** RegularExpression Id. */
    int NUMBER = 11;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = { "<EOF>", "\" \"", "\"\\n\"", "\"\\r\"",
            "\"\\r\\n\"", "\"oplus\"", "\"(\"", "\")\"", "\"[\"", "\"]\"",
            "\",\"", "<NUMBER>", };

}
